name: climbing_scores_web
channels:
  - anaconda-fusion
  - defaults
dependencies:
  - python=3.9
  - pip
  - flask
  - flask-bootstrap
  - pytest
  - requests
  - pandas
  - seaborn
  - gunicorn
  - python-dateutil
  - pip:

